"""add username to profiles

Revision ID: 5bb227435e5a
Revises: a953fb9893d5
Create Date: 2025-11-18 18:05:46.097172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb227435e5a'
down_revision: Union[str, Sequence[str], None] = 'a953fb9893d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meal_nutrition_id'), 'meal_nutrition', ['id'], unique=False)
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.add_column('profiles', sa.Column('username', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_unique_constraint(None, 'profiles', ['username'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_column('profiles', 'username')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_index(op.f('ix_meal_nutrition_id'), table_name='meal_nutrition')
    # ### end Alembic commands ###
