"""full profile fields

Revision ID: cf00e04be794
Revises: 5bb227435e5a
Create Date: 2025-11-18 18:15:15.191388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf00e04be794'
down_revision: Union[str, Sequence[str], None] = '5bb227435e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('food_allergies', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'food_allergies')
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###
